#Authentication types: in-memory, jdbc-authentication, jpa-authentication, ldap-authentication
authentication-type: ldap-authentication

spring:
  datasource:
    driverClassName: org.h2.Driver
    initialization-mode: always # Required for loading .sql files
    jdbc-url: jdbc:h2:mem:jdbcdb
    password: ''
    username: sa
    continue-on-error: true
    
  postgres-datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: always # Required for loading .sql files
    jdbcUrl: jdbc:postgresql://localhost/Springsecurity
    password: password
    username: postgres
    continue-on-error: true
  
  ldap:
    embedded:
      port: 8389
      ldif: classpath:ldap-data.ldif #ldif --> LDAP data interchange format
      base-dn: dc=springframework,dc=org

logging:
  level:
    org.springframework: INFO
